stages:
  preprocess:
    cmd: python src/preprocess.py 
    deps:
      - src/preprocess.py 
      - data/raw/raw_data.csv
    params:
      - preprocess.method
      - preprocess.window
    outs:
      - data/processed/df_train.csv 
      - data/processed/df_test.csv 

  train:
    cmd: python src/train.py 
    deps:
      - src/train.py
      - data/processed/df_train.csv 
      - data/processed/df_test.csv
    params:
      - train.transform
      - train.base
      - train.hyperparameters

  evaluate:
    cmd: python src/evaluate.py 
    deps:
      - src/evaluate.py
      - models/prophet_model.pkl
      - data/processed/df_test.csv
    params:
      - evaluate.transform
      - evaluate.base
